#get Users
###
GET http://localhost:5000/api/users


#get users
###
GET http://localhost:5000/api/users/65f6cdb7049575988407e425


# delete user
###
DELETE http://localhost:5000/api/users/65f6cdb7049575988407e425

# login user
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "kofiarhin@gmail.com",
    "password": "password"
}

# logout user
###
GET http://localhost:5000/api/auth/logout

# check auth 
###
GET http://localhost:5000/api/check

# register user
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "john doe ",
    "email": "johndoe@gmail.com",
    "password": "password",
    "location": "sheffield",
    "dob": "2002-02-01",
    "phoneNumber": "234324324324",
    "instagramUrl": "some instagram handle", 
    "userType": "photographer"
}